# This is an example Compose file
# Please use your own in production
version: '3.7'

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: always
    networks:
      - internal
    volumes:
      - ./db:/data

  worker:
    image: ghcr.io/luludotdev/dreddit
    build: '.'
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - ./config/config.json:/app/config/config.json:ro

networks:
  internal:
